language: python
env:
- TOXENV=py27
install:
- pip install tox==1.7.0
script: tox
deploy:
  provider: pypi
  user: juanjbrown
  password:
    secure: p3tYaB9VFStXfzi89ncB/Dk/512L2cOY0yCgeXrIUyJDK7htPBIfaiDhE81o1+ymifg2ruDI82zi19saBh0KcPv4y327vRZQ1e4rP1p72OiYK9cJvcU4KE13WA4ajHMsdEUnov7Jcq+yb4u3SVbh+C6rmMEhhgRWEDnSQm7C/ADcETAium88TQtXCAewxCsjHsDNH1Lh6gooqAuY8uTTvqiZvaJEsua0/92kNis3P828s6F4HgELJYpkHN1m8F2OaVdKDS4vMxzgv/wYqllQxN+fCkWxh7eg07DOPj+2qnuBcpnxR0zTr4T/eVQF6NiNj/+KiWqvld1uGGviaV5b2DL3azMswZtjl/ZahVcIWLvtfYVgFRdxoYUOFak2NgmZLRPoucJn7MrQ0osfnH2yjNyhYUm2/R8ErHVxInRaqIYYgpGq32NnEH/LATBBiKQUc7suB0e4PJHXSKHxrXRn+Y7TeX7LhV9t19Q2LGGXviVJvAeURWz+tB1cJqWAOiRTREl06tK8a13mO+ejx1jQbXQCfIf+WiiGDwEwuehqBkTEHGTZIbI2GeQlTvfqVg1pHqARovvWO9IZqcdgsATGrIgR7AzF5/OAz+J5+CR5J8caiIPbSOtxz/Jxmog9D+JcxVUUU77CdA85z1o/FsuNvmM5Wj/uB7JE3Y+T9t4h8PM=
  on:
    tags: true
    all_branches: true
    repo: juanjbrown/python-decouple-plus
